services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:123@db:5432/postgres?schema=SCHEMA
      - NODE_ENV=production
    depends_on:
      - db
    networks:
      - incubus-network

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - incubus-network

volumes:
  postgres_data:

networks:
  incubus-network:
    driver: bridge